[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "lambda"
version = "0.0.0"
dependencies = [
    "pandas>=2.0.0",
    "psycopg2-binary>=2.9.0",
    "python-dotenv>=1.0.0",
    "loguru>=0.7.0",
] 